language: rust

services:
  - docker

before_install:
  - rustup component add rustfmt
script:
  -  echo "$DOCKER_PASSWORD" | docker login quay.io --username "$DOCKER_USERNAME" --password-stdin && cargo fmt --all -- --check && cargo test
